# Generated by Django 3.1.7 on 2022-04-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitmodel',
            name='author',
            field=models.CharField(default='jake', max_length=100),
            preserve_default=False,
        ),
    ]
