# Generated by Django 3.1.7 on 2022-04-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_submitmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
